ansible_managed: managed by Ansible
warewulf_managed: managed by warewulf

# possibly opnsense vm only
opnsense_module_defaults:
  firewall: "{{ hostvars[groups.gateway_vm | first].ansible_host }}"
  api_key: "{{ opnsense_api_key }}"
  api_secret: "{{ opnsense_api_secret }}"
  ssl_verify: false

local_proxmox_ca_path: "/tmp/proxmox-ca-{{ groups.gateway_node | first }}.pem"
proxmox_module_defaults:
  api_host: "{{ hostvars[groups.gateway_node | first].ansible_host }}"
  api_user: root@pam
  api_password: "{{ proxmox_password }}"
  ca_path: "{{ local_proxmox_ca_path }}"

opnsense_api_delegate: "{{ groups.gateway_node | first }}"

dns_server: "{{ hostvars[groups.dns_vm | first].ansible_host }}"
k3s_traefik: "{{ hostvars[groups.k3s_control_plane | first].ansible_host }}:80"

markers_dir: "{{ inventory_dir }}/markers"
hardening_lockout_guard_marker: "{{ markers_dir }}/hardening-lockout-guard"

warewulf_temp_data:
  dataset: "{{ storage_pool.name }}/warewulf-node-temp"
  storage_gb: 16

k3s_persistent_data:
  dataset_suffix: "k3s-data"
  dataset: "{{ storage_pool.name }}/{{ k3s_persistent_data.dataset_suffix }}"
