ansible_user: root
ansible_python_interpreter: /usr/bin/python3
ansible_ssh_common_args: -o StrictHostKeyChecking=accept-new

netbird_server_version: "0.77.1"
netbird_dashboard_version: "v2.91.1"
kea_version: "3.0.4"
stork_version: "2.4.1"
warewulf_version: "4.7.0"
k3s_version: "v1.36.4+k3s1" # this affects both the control plane vm and warewulf agent nodes
pihole_version: "2026.07.2"

timezone: America/Los_Angeles

public_domain: ***REMOVED***
dns_upstreams:
  - 1.1.1.1
  - 1.0.0.1

iscsi_initiator_iqn_base: ***REMOVED***
iscsi_target_iqn_base: iqn.2005-10.org.freenas.ctl # truenas

public_ssh_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCnboXZxkQPUckgMBTycafCebFMm7pHamiyApuD1a/Nhr5o+BRsHnZA27ngCgwNbpLlVtt18pDMRlTR3QWf0Vgu3YekYhL5zm7R/o46b9nHp1JwuRO6kfYaOlXz65KbwjHgeb4d5Nwk3V2YJq7cpiAsFibExkJO6ieY1LSEldJJP7izLmf0+RitqoyyaUdVJrNA9q1bbY9AJjo1Gs1SpXtg/BPROnTjAxwftsR68vZtOkS7ytb0ml64XQ6xLs7BI4NyQaxAbMcAjcwqu1JCF+h2fNjZJPIt0LkFaZtbcsMEPixYvBgNYXoo5sFqqFFLLwie16DWx2EG9Zql1Bx+pik3jEPginqWwAbikWpHa40VKZ3Xb2Y/5ja/OkCAs9pbirK6B6MYmaFIck4Qgyn3afdHj4qyLeronw2SGcw3mUSBZ3CSRB7oXrohBQJIHrCd9d9Dx5JJ0WRd6wcLRxx/f1BcvdDio3T696a+IhcsbPKZrmzHjX3nlLfNmHormD4zjiiBixg+pnVSEzDnbt7jmjkN76OqCa0PmY3jifuqIhqEtTKYbrPUo7t8KEKqkskCN6wS0683MqxidwEn2JoKLYZxzlPmJOSqMj28cWhkkO1FWYdVSer5LWJOqqit+RupS5fd5/5jsStJAMQy//eqShp1VbZi2RaX9Yz6RenG+qkFwQ== timothy@Timothys-MacBook-Pro.local

opnsense_iso_image:
  base_url: "https://pkg.opnsense.org/releases/26.7"
  file: OPNsense-26.7-dvd-amd64.iso
  compression: bz2
  checksum: "sha256:{{ opnsense_iso_image.base_url }}/OPNsense-26.7-checksums-amd64.sha256"
  
debian_cloud_image:
  suite: trixie
  base_url: https://cloud.debian.org/images/cloud/trixie/20260819-2575
  file: debian-13-genericcloud-amd64-20260819-2575.qcow2
  checksum: "sha512:{{ debian_cloud_image.base_url }}/SHA512SUMS"

rocky_cloud_image:
  base_url: https://dl.rockylinux.org/pub/rocky/9/images/x86_64
  file: Rocky-9-GenericCloud-Base-9.8-20260525.0.x86_64.qcow2
  checksum: "sha256:{{ rocky_cloud_image.base_url }}/{{ rocky_cloud_image.file }}.CHECKSUM"

static_rules:
  - name: allow v4 lan traffic
    interface: [lan]
    source_net: lan
    ip_protocol: inet

homelab_networks:
  - name: main
    cidr: 10.127.0.0/24

# names must be alphanumberic + underscores
services:
  # - name: https_test2
  #   protocol: tcp
  #   ports: "1,70,8000-8010"
  #   dest: 10.127.0.50
  # - name: asdf
  #   protocol: tcp
  #   ports: "80"
  #   dest: 10.127.0.50
  #   dest_port: 8080
  - name: reverse_proxy
    protocol: tcp
    ports: "80,443"
    dest: "{{ hostvars[groups.rev_proxy_vm | first].ansible_host }}"

proxy_routes:
  - host: "{{ netbird_domain }}"
    backend: "{{ hostvars[groups.netbird_vm | first].ansible_host }}:{{ hostvars[groups.netbird_vm | first].netbird_dashboard_port }}"
    grpc_backend: "{{ hostvars[groups.netbird_vm | first].ansible_host }}:{{ hostvars[groups.netbird_vm | first].netbird_server_port }}"
  - host: "ai.***REMOVED***"
    backend: "10.127.0.100:8080"
