- name: set up truenas k3s storage
  hosts: storage
  tasks:
    - ansible.builtin.import_role:
        name: truenas
        tasks_from: k3s_storage

- name: set up k3s control plane
  hosts: k3s_control_plane
  gather_facts: false
  tasks:
    - ansible.builtin.import_role:
        name: k3s_control_plane

- name: set up warewulf
  hosts: warewulf_vm
  gather_facts: false
  tasks:
    - ansible.builtin.import_role:
        name: warewulf

- name: set up kea
  hosts: kea_vm
  gather_facts: false
  tasks:
    - ansible.builtin.import_role:
        name: kea
