- name: set up truenas temp disk storage for warewulf nodes
  hosts: storage
  tasks:
    - ansible.builtin.import_role:
        name: truenas
        tasks_from: warewulf_temp_storage

# consider merging with above?
- name: setup k3s persistent storage
  hosts: storage
  tasks:
    - ansible.builtin.import_role:
        name: truenas
        tasks_from: k3s_persistent_storage

- name: set up k3s control plane
  hosts: k3s_control_plane
  gather_facts: false
  tasks:
    - ansible.builtin.import_role:
        name: k3s
        tasks_from: k3s_control_plane

- name: set up warewulf
  hosts: warewulf_vm
  gather_facts: false
  tasks:
    - ansible.builtin.import_role:
        name: warewulf

- name: set up kea
  hosts: kea_vm
  gather_facts: false
  tasks:
    - ansible.builtin.import_role:
        name: kea

- name: set up k3s agent vms
  hosts: warewulf_nodes
  gather_facts: false
  tasks:
    - ansible.builtin.import_role:
        name: k3s
        tasks_from: k3s_vms
