- name: update initramfs
  ansible.builtin.command: update-initramfs -u -k all
  changed_when: true
  
- name: reboot
  ansible.builtin.reboot:

- name: update interfaces
  ansible.builtin.command: ifreload -a
  changed_when: true

- name: update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: restart pveproxy
  ansible.builtin.systemd_service:
    name: pveproxy
    state: restarted
