all:
  # the unique definition of each host
  hosts:
    # nodes
    # can be named freely
    pavo:
      ansible_host: 10.127.0.1
    carina:
      ansible_host: 10.127.0.2
      ansible_ssh_common_args: '-J {{ hostvars["pavo"]["ansible_host"] }}'

    # vms
    # cannot be named freely
    gateway_vm:
      ansible_host: 10.127.0.254
      ansible_ssh_common_args: '-J {{ hostvars["pavo"]["ansible_host"] }}'
    mgmt_warewulf_vm:
      ansible_host: 10.127.0.253
    mgmt_netbird_vm:
      ansible_host: 10.127.0.252

  # classifying the hosts above into the generic named groups the roles execute on
  children:
    # requirements: =1 server, running proxmox
    gateway_node:
      hosts:
        pavo:
      vars:
        lan_ip: 10.127.0.1
        wan_ip: 192.168.4.75
        wan_mac: ***REMOVED***
        lan_mac: ***REMOVED***
    # requirements: =1 server, running proxmox
    mgmt_node:
      hosts:
        pavo:
    # requirements: =1 server, running truenas
    storage_node:
      hosts:
        carina: