all:
  # the unique definition of each host
  hosts:
    # nodes
    pavo:
      ansible_host: 10.127.0.1
    carina:
      ansible_host: 10.127.0.2
      ansible_user: truenas_admin # todo: has to be here to override group var rn; will fix later
    tunnel:
      ansible_host: ***REMOVED***
      ansible_port: 2222
      ansible_user: ubuntu
      ansible_become: true
    
    # physical warewulf nodes
    # todo: the next install these ips should be different (including the vm one)
    pisces:
      ansible_host: 10.127.0.123
      mac: ***REMOVED***
    corvus:
      ansible_host: 10.127.0.122
      mac: ***REMOVED***
    dorado:
      ansible_host: 10.127.0.121
      mac: ***REMOVED***

    # single purpose vms
    # cannot be named freely
    gateway_vm01:
      ansible_host: 10.127.0.254
      vm_config:
        template: iso
        id: 254
        node: "{{ groups.gateway_node | first }}"
        image: "{{ opnsense_iso_image }}"
        memory_mb: 6144 # this can be decreased to 4096 after install
        net:
          net0: virtio,bridge=vmbr0,firewall=0
          net1: virtio,bridge=vmbr1,firewall=0

    rev_proxy_vm01:
      ansible_host: 10.127.0.253
      vm_config:
        template: cloud
        id: 253
        node: "{{ groups.gateway_node | first }}"

    netbird_vm01:
      ansible_host: 10.127.0.252
      vm_config:
        template: cloud
        id: 252
        node: "{{ groups.mgmt | first }}"
    
    kea_vm01:
      ansible_host: 10.127.0.251
      vm_config:
        template: cloud
        id: 251
        node: "{{ groups.mgmt | first }}"
        agent: false

    warewulf_vm01:
      ansible_host: 10.127.0.250
      ansible_user: rocky # todo: has to be here to override group var rn; will fix later
      ansible_become: true
      vm_config:
        template: cloud
        id: 250
        image: "{{ rocky_cloud_image }}"
        node: "{{ groups.mgmt | first }}"
        memory_mb: 4096
        storage_gb: 32
    
    k3s_control_plane_vm01:
      ansible_host: 10.127.0.249
      vm_config:
        template: cloud
        id: 249
        node: "{{ groups.mgmt | first }}"
        memory_mb: 4096
        storage_gb: 32

    # virtual warewulf nodes
    virgo:
      ansible_host: 10.127.0.120
      mac: 00:00:00:00:01:20
      vm_config:
        template: pxe
        id: 120
        node: "{{ groups.gateway_node | first }}"

  # classifying the hosts above into the generic named groups the roles execute on
  children:
    # requirements: =1 server, running proxmox
    # role: runs gateway vm, has nic to home router
    gateway_node:
      hosts:
        pavo:
      vars:
        lan_ip: 10.127.0.1 # duplicated earlier in file, should fix at some point
        wan_ip: 192.168.4.75
        wan_mac: ***REMOVED***
        lan_mac: ***REMOVED***
    
    gateway_vm:
      hosts:
        gateway_vm01:
      vars:
        tunnel_ip: 10.127.1.1
        wg_iface_name: opt1
        tunnel_peer: "{{ hostvars[groups.public_relay | first] }}"
    
    rev_proxy_vm:
      hosts:
        rev_proxy_vm01:
    
    netbird_vm:
      hosts:
        netbird_vm01:
      vars:
        netbird_dashboard_port: 8080
        netbird_server_port: 8081
    
    generic_deb_vms:
      children:
        rev_proxy_vm:
        netbird_vm:
    
    kea_vm:
      hosts:
        kea_vm01:
    
    warewulf_vm:
      hosts:
        warewulf_vm01:
    
    k3s_control_plane:
      hosts:
        k3s_control_plane_vm01:
    
    warewulf_nodes:
      hosts:
        pisces:
        corvus:
        dorado:
        virgo:

    internal:
      children:
        mgmt:
        storage:
        gateway_vm:
        generic_deb_vms:
        kea_vm:
        warewulf_vm:
        k3s_control_plane:
        warewulf_nodes:

    # requirements: =1 server, running proxmox
    # role: runs warewulf
    mgmt:
      hosts:
        pavo:

    # requirements: =1 server, running truenas
    # role: provides storage
    storage:
      hosts:
        carina:
      vars:
        storage_pool:
          name: main
          type: STRIPE
          disks:
            - ***REMOVED***

    # requirements: =1 server, running ubuntu, public ipv4
    # role: wireguard, dnat relay w/ public ip
    public_relay:
      hosts:
        tunnel:
      vars:
        tunnel_ip: 10.127.1.2
        tunnel_port: 51820
        tunnel_peer: "{{ hostvars[groups.gateway_vm | first] }}"
        public_ip: ***REMOVED***
        wan_interface: ens3
