all:
  # the unique definition of each host
  hosts:
    # nodes
    pavo:
      ansible_host: 10.127.0.1
    carina:
      ansible_host: 10.127.0.2
    tunnel:
      ansible_host: ***REMOVED***
      ansible_port: 2222
      ansible_user: ubuntu
      ansible_become: true

    # single purpose vms
    # cannot be named freely
    gateway_vm01:
      ansible_host: 10.127.0.254
      vm_id: 254
      vm_storage_gb: 16

    rev_proxy_vm01:
      ansible_host: 10.127.0.253
      vm_id: 253
      vm_storage_gb: 16

    netbird_vm01:
      ansible_host: 10.127.0.252
      vm_id: 252
      vm_storage_gb: 16

    warewulf_vm01:
      ansible_host: 10.127.0.250
      vm_id: 250
      vm_storage_gb: 32
      ansible_user: rocky # fixed
      ansible_become: true # fixed
      ansible_ssh_common_args: -o StrictHostKeyChecking=accept-new # fixed

  # classifying the hosts above into the generic named groups the roles execute on
  children:
    # requirements: =1 server, running proxmox
    # role: runs gateway vm, has nic to home router
    gateway_node:
      hosts:
        pavo:
      vars:
        lan_ip: 10.127.0.1 # duplicated earlier in file, should fix at some point
        wan_ip: 192.168.4.75
        wan_mac: ***REMOVED***
        lan_mac: ***REMOVED***
    
    gateway_vm:
      hosts:
        gateway_vm01:
      vars:
        tunnel_ip: 10.127.1.1
        wg_iface_name: opt1
        tunnel_peer: "{{ hostvars[groups.public_relay | first] }}"
    
    rev_proxy_vm:
      hosts:
        rev_proxy_vm01:
    
    netbird_vm:
      hosts:
        netbird_vm01:
      vars:
        netbird_dashboard_port: 8080
        netbird_server_port: 8081
        netbird_server_version: "0.77.1"
        netbird_dashboard_version: "v2.91.1"
    
    generic_deb_vms:
      children:
        rev_proxy_vm:
        netbird_vm:
      vars:
        vm_cores: 2
        vm_memory_mb: 2048
    
    warewulf_vm:
      hosts:
        warewulf_vm01:
      vars:
        vm_cores: 2
        vm_memory_mb: 2048

    # requirements: =1 server, running proxmox
    # role: runs warewulf
    mgmt:
      hosts:
        pavo:

    # requirements: =1 server, running truenas
    # role: provides storage
    storage:
      hosts:
        carina:
      vars:
        ansible_user: truenas_admin
        storage_pool:
          name: main
          type: STRIPE
          disks:
            - ***REMOVED***

    # requirements: =1 server, running ubuntu, public ipv4
    # role: wireguard, dnat relay w/ public ip
    public_relay:
      hosts:
        tunnel:
      vars:
        tunnel_ip: 10.127.1.2
        tunnel_port: 51820
        tunnel_peer: "{{ hostvars[groups.gateway_vm | first] }}"
        public_ip: ***REMOVED***
        wan_interface: ens3

    # k3s:
    #   hosts:
    #     pisces:
    #     corvus:
    #     dorado:
    #     virgo:
