- vars:
    proxmox_node: "{{ groups.mgmt | first }}"
  module_defaults:
    group/community.proxmox.proxmox: "{{ proxmox_module_defaults }}"
  when: vm_id is defined
  block:
    - ansible.builtin.import_role:
        name: bootstrap
        tasks_from: fetch_proxmox_ca.yml

    - name: create vm
      community.proxmox.proxmox_kvm:
        name: "{{ inventory_hostname | replace('_', '-') }}"
        node: "{{ proxmox_node }}"
        vmid: "{{ vm_id }}"
        bios: ovmf
        onboot: true
        cpu: host
        cores: "{{ vm_cores }}"
        memory: "{{ vm_memory_mb }}"
        scsihw: virtio-scsi-single
        boot: "order=net0"
        agent: true
        efidisk0:
          storage: local-lvm
          format: raw
          efitype: 4m
          pre_enrolled_keys: false
        net:
          net0: "virtio={{ mac }},bridge=vmbr1,firewall=0"
        serial:
          serial0: socket
      delegate_to: localhost

    - name: start vm
      community.proxmox.proxmox_kvm:
        vmid: "{{ vm_id }}"
        node: "{{ proxmox_node }}"
        state: started
      delegate_to: localhost

    # warewulf vms cannot use wait_for_connection as that requires python on the target
    - name: wait for ssh
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: 22
        timeout: 120
      delegate_to: localhost
