- name: write caddyfile
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    mode: "644"
    validate: caddy validate --adapter caddyfile --config %s
  notify: reload caddy
