- name: apply firewall aliases
  oxlorg.opnsense.raw:
    module: firewall
    controller: alias
    command: reconfigure
    action: post

- name: apply firewall rules
  oxlorg.opnsense.raw:
    module: firewall
    controller: filter
    command: apply
    action: post

- name: apply unbound
  oxlorg.opnsense.raw:
    module: unbound
    controller: service
    command: reconfigure
    action: post