- name: install warewulf and tftp server
  ansible.builtin.dnf:
    name:
      - "{{ warewulf_rpm_url }}"
      - tftp-server
    state: present
    disable_gpg_check: true

# adds to root despite ansible_user being rocky as this gets copied to all nodes
- name: add authorized key for node root logins
  ansible.posix.authorized_key:
    user: root
    key: "{{ public_ssh_keys | join('\n') }}"

- name: configure warewulf
  ansible.builtin.template:
    src: warewulf.conf.j2
    dest: /etc/warewulf/warewulf.conf
    owner: root
    group: root
    mode: "644"
  register: warewulf_conf
  notify: restart warewulf

- name: enable warewulf
  ansible.builtin.systemd_service:
    name: warewulfd
    enabled: true
    state: started

- name: check if configuration has ran before
  ansible.builtin.stat:
    path: /var/lib/tftpboot/warewulf/ipxe-snponly-x86_64.efi
  register: warewulf_bootfile

- name: apply warewulf configuration
  ansible.builtin.command: wwctl configure --all
  when: warewulf_conf.changed or not warewulf_bootfile.stat.exists
  changed_when: true

- name: check if node image exists
  ansible.builtin.stat:
    path: "{{ warewulf_chroot }}"
  register: warewulf_image_chroot

- name: import node image
  ansible.builtin.command: wwctl image import {{ warewulf_image_source }} {{ warewulf_image_name }}
  notify: build node image
  when: not warewulf_image_chroot.stat.exists
  changed_when: true

# todo: this is just temporary
- name: set root password in node image
  ansible.builtin.command: >-
    wwctl image exec --build=false {{ warewulf_image_name }} -- /bin/bash -c "echo root:{{ temp_password }} | chpasswd"
  no_log: true
  notify: build node image
  changed_when: false # this is not true

- name: ensure andromeda directory exists
  ansible.builtin.file:
    path: "{{ warewulf_chroot }}/andromeda"
    state: directory
    mode: "755"

- name: read image package list
  ansible.builtin.slurp:
    src: "{{ warewulf_chroot }}/andromeda/warewulf-packages"
  register: image_package_list
  failed_when: false

- name: install packages to image
  ansible.builtin.command: >-
    wwctl image exec --build=false {{ warewulf_image_name }} --
    /bin/bash -c "apt-get update && apt-get install -y --no-install-recommends {{ warewulf_image_packages | join(' ') }} && rm -rf /var/lib/apt/lists/*"
  notify: build node image
  when: (image_package_list.content | default('') | b64decode) != (warewulf_image_packages | join('\n'))
  changed_when: true

- name: write image package list
  ansible.builtin.copy:
    content: "{{ warewulf_image_packages | join('\n') }}"
    dest: "{{ warewulf_chroot }}/andromeda/warewulf-packages"
    mode: "644"

- name: enforce locale because lean image
  ansible.builtin.copy:
    content: "SetEnv LANG=C.UTF-8\n"
    dest: "{{ warewulf_chroot }}/etc/ssh/sshd_config.d/99-locale.conf"
    mode: "644"
  notify: build node image

- name: install k3s agent to image
  args:
    creates: "{{ warewulf_chroot }}/etc/systemd/system/k3s-agent.service"
  ansible.builtin.command: >-
    wwctl image exec --build=false {{ warewulf_image_name }} --
    /bin/bash -c "curl -sfL https://get.k3s.io |
    INSTALL_K3S_SKIP_ENABLE=true
    INSTALL_K3S_EXEC=agent
    INSTALL_K3S_VERSION={{ k3s_version }}
    sh -s -"
  notify: build node image

# unlike the overlays below this is a direct modification to the image
- name: enable k3s agent in image
  ansible.builtin.file:
    src: ../k3s-agent.service
    dest: "{{ warewulf_chroot }}/etc/systemd/system/multi-user.target.wants/k3s-agent.service"
    state: link
    force: true
  notify: build node image

- name: create journald config directory in image
  ansible.builtin.file:
    path: "{{ warewulf_chroot }}/etc/systemd/journald.conf.d/"
    state: directory
    mode: "755"

- name: write journald config to image
  ansible.builtin.template:
    src: 50-ephemeral-journald.conf.j2
    dest: "{{ warewulf_chroot }}/etc/systemd/journald.conf.d/50-ephemeral-journald.conf"
    mode: "644"
  notify: build node image

- name: create overlays
  module_defaults:
    ansible.builtin.template:
      variable_start_string: "[["
      variable_end_string: "]]"
  block:
    - name: create overlay directories
      ansible.builtin.file:
        path: "{{ warewulf_overlay_dir }}/{{ item }}"
        state: directory
        mode: "755"
      loop:
        - iscsi.initiator/rootfs/etc/iscsi
        - k3s.storage/rootfs/etc/systemd/system/multi-user.target.wants
        - k3s.agent/rootfs/etc/systemd/system/k3s-agent.service.d
        - k3s.agent/rootfs/etc/rancher/k3s/config.yaml.d
        - k3s.agent/rootfs/etc/rancher/node
      
    - name: write iscsi initiator overlay
      ansible.builtin.template:
        src: initiatorname.iscsi.ww.j2
        dest: "{{ warewulf_overlay_dir }}/iscsi.initiator/rootfs/etc/iscsi/initiatorname.iscsi.ww"
        mode: "644"
      notify: build overlays

    - name: write k3s storage service overlays
      ansible.builtin.template:
        src: "k3s-iscsi.service.ww.j2"
        dest: "{{ warewulf_overlay_dir }}/k3s.storage/rootfs/etc/systemd/system/k3s-iscsi.service.ww"
        mode: "644"
      notify: build overlays

    - name: run k3s storage service on startup
      ansible.builtin.file:
        src: "../k3s-iscsi.service"
        dest: "{{ warewulf_overlay_dir }}/k3s.storage/rootfs/etc/systemd/system/multi-user.target.wants/k3s-iscsi.service"
        state: link
        force: true
      notify: build overlays

    - name: write node temp directory service overlay
      ansible.builtin.template:
        src: node-temp-dirs.service.j2
        dest: "{{ warewulf_overlay_dir }}/k3s.storage/rootfs/etc/systemd/system/node-temp-dirs.service"
        mode: "644"
      notify: build overlays

    - name: wire k3s agent storage dependency overlay
      ansible.builtin.template:
        src: 50-storage.conf.j2
        dest: "{{ warewulf_overlay_dir }}/k3s.agent/rootfs/etc/systemd/system/k3s-agent.service.d/50-storage.conf"
        mode: "644"
      notify: build overlays

    - name: read k3s token
      ansible.builtin.slurp:
        path: /var/lib/rancher/k3s/server/node-token
      delegate_to: "{{ groups.k3s_control_plane | first }}"
      register: k3s_token_file
      no_log: true

    - name: write k3s agent config
      ansible.builtin.template:
        src: 50-k3s-agent-config.yaml.j2
        dest: "{{ warewulf_overlay_dir }}/k3s.agent/rootfs/etc/rancher/k3s/config.yaml.d/50-k3s-agent-config.yaml"
        mode: "600"
      no_log: true
      notify: build overlays

    - name: write k3s node password
      ansible.builtin.template:
        src: k3s-node-password.ww.j2
        dest: "{{ warewulf_overlay_dir }}/k3s.agent/rootfs/etc/rancher/node/password.ww"
        mode: "600"
      no_log: true
      notify: build overlays

- name: write nodes config
  ansible.builtin.template:
    src: nodes.conf.j2
    dest: /etc/warewulf/nodes.conf
    mode: "644"
  notify:
    - build overlays
    - reload warewulf
