warewulf_rpm_url: "https://github.com/warewulf/warewulf/releases/download/v{{ warewulf_version }}/warewulf-{{ warewulf_version }}-1.el9.x86_64.rpm"
warewulf_network: "{{ homelab_networks[0].cidr }}"

warewulf_image_name: debian-13
warewulf_image_source: docker://ghcr.io/warewulf/warewulf-debian:13

warewulf_chroot: "/var/lib/warewulf/chroots/{{ warewulf_image_name }}/rootfs"
warewulf_overlay_dir: /var/lib/warewulf/overlays

warewulf_storage_host: "{{ hostvars[groups.storage | first].ansible_host }}"

warewulf_node_temp_mount: /mnt/node-temp
warewulf_node_temp_binds:
  - /var/lib/rancher/k3s # where container images are stored
  - /var/lib/kubelet # where emptyDir file systems are stored
  - /var/log/pods # container logs

warewulf_custom_system_overlays:
  - iscsi.initiator
  - k3s.storage
  - k3s.agent

warewulf_image_packages:
  - nfs-common # truenas nfs storage
  - open-iscsi # truenas zvol block stoage
  - e2fsprogs # truenas
  - conntrack # kube-proxy
  - socat # kubectl port-forward
  - iptables
  - curl
  - iputils-ping
  - htop
  - bind9-dnsutils # dns debug
  - less
  - vim
  - lsof
  - tcpdump
  - jq
  - bash-completion
  - net-tools
  - systemd-timesyncd # ntp time sync
